# Generated by Django 3.0.5 on 2020-04-12 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('floorplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='json_path',
            field=models.FileField(default=django.utils.timezone.now, upload_to='jsons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='image'),
        ),
    ]
